# Generated by Django 3.0.2 on 2020-02-26 12:54

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('car_image', models.ImageField(upload_to='car_images')),
                ('car_rent', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('city_image', models.ImageField(upload_to='city_images')),
                ('city_summary', models.CharField(max_length=200)),
                ('city_color', colorful.fields.RGBColorField(colors=['#FF0000', '#00FF00', '#0000FF'], default=0)),
            ],
            options={
                'ordering': ['city_name'],
            },
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=20)),
                ('place_intro', models.TextField(default=None)),
                ('place_images', models.ImageField(upload_to='place_images')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.city')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
